### ISSUE TITLE
how to see the file order?

### ISSUE THREAD

**Issue by thearabbit** [Elfoslav/meteor-files-order#1]
I use chrome bowser, but don't see anything.

**Comment by Elfoslav** [comment]
Open your developers console, press F12 key and you will see:

![screenshot from 2015-01-17 03 32 58](https://cloud.githubusercontent.com/assets/1983575/5787313/c1d5f928-9df9-11e4-8d57-e76bb884952d.png)

**Comment by thearabbit** [comment]
very thanks, i will try
